### ISSUE TITLE
Damage calculation issue

### ISSUE THREAD

**Issue by sirjonathan** [amigobrewbrew/polytopiacalculatorfirebase-public#7] opened 2024-05-09 15:08 UTC
![image](https://github.com/amigobrewbrew/polytopiacalculatorfirebase-public/assets/104149/265686af-b50d-4c41-ba22-91bbe0ba71a8)

![image](https://github.com/amigobrewbrew/polytopiacalculatorfirebase-public/assets/104149/e244df51-0b57-42e5-98bb-c444679f7342)

Bomber damage against dragon seems to be off. Calculator suggests 10 damage when in reality it only did 5.

**Comment by amigobrewbrew** [comment] 2024-05-12 23:23
Thanks. Many issues reported with bomber. Not sure about the cause yet...

**Comment by matiasanaya** [comment] 2024-05-27 14:57
To be fair, that dragon has a defense bonus. Regardless, the calculator reports 15 -> 7 which seems to still be off.

**Comment by trigaten** [comment] 2024-06-07 19:30
@amigobrewbrew i think bomber damaged changed to 3 rather than 4, which is why the calculations may be off.

PS, I use this website like every other day, super helpful :)

**Comment by amigobrewbrew** [comment] 2024-06-25 20:01
> @amigobrewbrew i think bomber damaged changed to 3 rather than 4, which is why the calculations may be off.
> 
> PS, I use this website like every other day, super helpful :)

That had been updated a while ago though...

**Comment by amigobrewbrew** [comment] 2024-06-25 20:23
![2024-06-25_16-23-14](https://github.com/amigobrewbrew/polytopiacalculatorfirebase-public/assets/57629953/e928d59d-bcc6-4d3d-850a-de2a325ebc7d)

I think the bomber splashed something? Instead of directly attacking the baby dragon?

**Comment by amigobrewbrew** [comment] 2024-09-08 21:48
This should be fixed now
![Screenshot_20240908_234617_Chrome](https://github.com/user-attachments/assets/0907a0a4-1685-4acc-b8cc-c3ed08dad109)

**Closed by amigobrewbrew** 2024-09-08 21:48 UTC
